/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 04-sep.-2019 10:45:43 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

CREATE DATABASE banco;
/* Create Tables */

CREATE TABLE `c_banco`
(
	`id` SMALLINT NOT NULL,
	`clave` VARCHAR(50) 	 NULL,
	`nombre_corto` VARCHAR(50) 	 NULL,
	`banco` TEXT 	 NULL,
	`id_status` TINYINT NOT NULL,
	`orden` SMALLINT 	 NULL,
	CONSTRAINT `PK_c_banco` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `c_cuentas_bancarias`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`alias` VARCHAR(50) NOT NULL,
	`id_banco` SMALLINT NOT NULL,
	`ultimos_digitos` VARCHAR(10) NOT NULL,
	CONSTRAINT `PK_c_cuentas_bancarias` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `c_cuentas_bancarias` 
 ADD INDEX `IXFK_c_cuentas_bancarias_c_banco` (`id_banco` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `c_cuentas_bancarias` 
 ADD CONSTRAINT `FK_c_cuentas_bancarias_c_banco`
	FOREIGN KEY (`id_banco`) REFERENCES `c_banco` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;

	CREATE VIEW obtenerCuentas AS
SELECT cuenta.*, banco.nombre_corto 
FROM c_cuentas_bancarias cuenta 
INNER JOIN c_bancos banco ON banco.id = cuenta.id_banco